import React from 'react';

const ExportPanel = ({ detections = [], selectedDetections = [] }) => {
    const exportToJSON = () => {
        const dataToExport = selectedDetections.length > 0 ? selectedDetections : detections;
        const jsonString = JSON.stringify(dataToExport, null, 2);
        const blob = new Blob([jsonString], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `sentinel-sea-detections-${new Date().toISOString().split('T')[0]}.json`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    };

    const exportToCSV = () => {
        const dataToExport = selectedDetections.length > 0 ? selectedDetections : detections;

        if (dataToExport.length === 0) {
            alert('No data to export');
            return;
        }

        // CSV Headers
        const headers = [
            'Detection ID',
            'Timestamp',
            'Latitude',
            'Longitude',
            'Vessel Size',
            'AIS Status',
            'Threat Score',
            'Review Status',
            'Inside MPA',
            'SAR Area (m²)',
            'SAR Intensity (dB)',
            'Elongation Ratio'
        ];

        // CSV Rows
        const rows = dataToExport.map(d => [
            d.vesselId,
            d.timestamp,
            d.latitude,
            d.longitude,
            d.vesselSize || 'N/A',
            d.aisStatus === 'OFF' ? 'OFF' : 'ON',
            d.threatScore,
            d.reviewed ? 'Reviewed' : 'Pending',
            d.inProtectedZone ? 'Yes' : 'No',
            d.sarFeatures?.area?.toFixed(2) || 'N/A',
            d.sarFeatures?.intensity?.toFixed(2) || 'N/A',
            d.sarFeatures?.elongation?.toFixed(2) || 'N/A'
        ]);

        // Build CSV string
        const csvContent = [
            headers.join(','),
            ...rows.map(row => row.map(cell => `"${cell}"`).join(','))
        ].join('\n');

        // Download
        const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `sentinel-sea-detections-${new Date().toISOString().split('T')[0]}.csv`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    };

    const exportSummaryReport = () => {
        const dataToExport = selectedDetections.length > 0 ? selectedDetections : detections;

        const stats = {
            totalDetections: dataToExport.length,
            anomalousVessels: dataToExport.filter(d => d.aisStatus === 'OFF').length,
            highThreat: dataToExport.filter(d => d.threatScore >= 70).length,
            mediumThreat: dataToExport.filter(d => d.threatScore >= 40 && d.threatScore < 70).length,
            lowThreat: dataToExport.filter(d => d.threatScore < 40).length,
            insideMPA: dataToExport.filter(d => d.inProtectedZone).length,
            unreviewed: dataToExport.filter(d => !d.reviewed).length
        };

        const reportContent = `
SENTINEL-SEA MARITIME SURVEILLANCE REPORT
Generated: ${new Date().toLocaleString()}
========================================

EXECUTIVE SUMMARY
-----------------
Total Detections: ${stats.totalDetections}
Anomalous Vessels (AIS OFF): ${stats.anomalousVessels}
Inside Marine Protected Areas: ${stats.insideMPA}
Pending Review: ${stats.unreviewed}

THREAT DISTRIBUTION
-------------------
High Threat (≥70):    ${stats.highThreat} detections
Medium Threat (40-69): ${stats.mediumThreat} detections
Low Threat (<40):     ${stats.lowThreat} detections

DETAILED DETECTIONS
-------------------
${dataToExport.map((d, i) => `
${i + 1}. ${d.vesselId}
   Time: ${d.timestamp}
   Location: ${d.latitude}°N, ${d.longitude}°E
   AIS Status: ${d.aisStatus}
   Threat Score: ${d.threatScore}%
   Inside MPA: ${d.inProtectedZone ? 'Yes' : 'No'}
   Vessel Size: ${d.vesselSize || 'Unknown'}
   Review Status: ${d.reviewed ? 'Reviewed' : 'Pending'}
`).join('\n')}

========================================
Report generated by Sentinel-Sea Maritime Surveillance System
    `.trim();

        const blob = new Blob([reportContent], { type: 'text/plain;charset=utf-8;' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `sentinel-sea-report-${new Date().toISOString().split('T')[0]}.txt`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    };

    return (
        <div className="bg-[#262626] rounded-lg p-4 border border-zinc-800">
            <h3 className="text-sm font-semibold text-zinc-300 uppercase tracking-wide mb-4 flex items-center gap-2">
                <svg className="w-5 h-5 text-zinc-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                </svg>
                Export Data
            </h3>

            <div className="space-y-2">
                <button
                    onClick={exportToCSV}
                    className="w-full flex items-center justify-between px-4 py-3 bg-[#1A1A1A] hover:bg-zinc-800 border border-zinc-700 hover:border-zinc-600 rounded transition-colors group"
                >
                    <div className="flex items-center gap-3">
                        <div className="w-8 h-8 bg-green-500/10 rounded flex items-center justify-center">
                            <span className="text-green-400 text-sm font-bold">CSV</span>
                        </div>
                        <div className="text-left">
                            <div className="text-sm font-semibold text-zinc-300">Export as CSV</div>
                            <div className="text-xs text-zinc-500">Excel-compatible spreadsheet</div>
                        </div>
                    </div>
                    <svg className="w-5 h-5 text-zinc-600 group-hover:text-zinc-400 transition-colors" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                    </svg>
                </button>

                <button
                    onClick={exportToJSON}
                    className="w-full flex items-center justify-between px-4 py-3 bg-[#1A1A1A] hover:bg-zinc-800 border border-zinc-700 hover:border-zinc-600 rounded transition-colors group"
                >
                    <div className="flex items-center gap-3">
                        <div className="w-8 h-8 bg-blue-500/10 rounded flex items-center justify-center">
                            <span className="text-blue-400 text-sm font-bold">JSON</span>
                        </div>
                        <div className="text-left">
                            <div className="text-sm font-semibold text-zinc-300">Export as JSON</div>
                            <div className="text-xs text-zinc-500">Machine-readable format</div>
                        </div>
                    </div>
                    <svg className="w-5 h-5 text-zinc-600 group-hover:text-zinc-400 transition-colors" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                    </svg>
                </button>

                <button
                    onClick={exportSummaryReport}
                    className="w-full flex items-center justify-between px-4 py-3 bg-[#1A1A1A] hover:bg-zinc-800 border border-zinc-700 hover:border-zinc-600 rounded transition-colors group"
                >
                    <div className="flex items-center gap-3">
                        <div className="w-8 h-8 bg-orange-500/10 rounded flex items-center justify-center">
                            <span className="text-orange-400 text-sm font-bold">TXT</span>
                        </div>
                        <div className="text-left">
                            <div className="text-sm font-semibold text-zinc-300">Summary Report</div>
                            <div className="text-xs text-zinc-500">Human-readable analysis</div>
                        </div>
                    </div>
                    <svg className="w-5 h-5 text-zinc-600 group-hover:text-zinc-400 transition-colors" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                    </svg>
                </button>
            </div>

            <div className="mt-4 p-3 bg-zinc-800/50 rounded">
                <div className="text-xs text-zinc-400">
                    {selectedDetections.length > 0 ? (
                        <><strong className="text-orange-400">{selectedDetections.length}</strong> selected detection{selectedDetections.length !== 1 ? 's' : ''} will be exported</>
                    ) : (
                        <><strong className="text-zinc-300">{detections.length}</strong> total detection{detections.length !== 1 ? 's' : ''} will be exported</>
                    )}
                </div>
            </div>
        </div>
    );
};

export default ExportPanel;
